# MESSAGE SUCCESS Codes
SUCCESS_OTP_SENT = "Verification Code Sent Successfully"
SUCCESS_EMAIL_SENT = "Email verification link has been sent successfully"
SUCCESS_LOGIN = "Login Successfully"
SUCCESS_DATA_RETRIEVED = "Data Retrieved successfully"
SUCCESS_FOUND = "Data is found"
SUCCESS_USER_FOUND = "User Found"
SUCCESS_PERMISSION_FOUND = "Permission Found"
SUCCESS_EMAIL_EXIST = "User with this email address already exists"
SUCCESS_USER_LOGOUT = "User Logout Successfully"
SUCCESS_USER_ALREADY_LOGOUT = "User Already Logout"
SUCCESS_UPDATED = "Data updated successfully"
SUCCESS_RESET_PASSWORD = 'Password reset successful'
SUCCESS_OTP_VERIFICATION = 'OTP verification successful'
SUCCESS_EMAIL_VERIFICATION = 'Email verification successful'

# ERROR Codes
ERROR_OCCURRED = "Some Error Occurred"
ERROR_CORRECT_PASSWORD = "Please enter correct password"
ERROR_EMAIL_DOES_NOT_EXIST = "No user is registered using this email address"
ERROR_CHECK_EMAIL_NOT_EXIST = "User with this email does not exist"
ERROR_OTP_WRONG = "Incorrect Verification Code"
ERROR_TOKEN_ENTER = 'Please Provide Token for Authorization.'
ERROR_TOKEN_EXPIRED = "Token has expired"
ERROR_USER_NOT_FOUND = "User not found"
ERROR_USER_INACTIVE = "User is inactive"
ERROR_DB = "Database Error Occurred"
ERROR_KEY = "Key Error Occurred"
ERROR_DATA = "Data Not Found"
ERROR_TECHNICAL = "Technical Error Occurred"
ERROR_BAD_REQUEST = "Bad Request"
ERROR_AUTH_FAILED = 'Authentication Failed / Token Invalid'
ERROR_AUTH_UNEXP = 'Authentication Failed Unexpectedly'
ERROR_AUTH_TOKEN = "Please enter valid Authorization Token"
ERROR_TYPE_NOT_RECEIVED = "User Not Authorized. Please Contact Admin"
ERROR_PERMISSION_DENIED = "Permission Denied"
ERROR_PERMISSION_NOT_EXISTS = 'Permission Does Not Exists'
ERROR_CONTACT_ADMINISTRATOR = "Please contact your Administrator"
ERROR_SESSION_EXPIRED = "You are Logged Out. Please Login Again"
ERROR_CONNECTING_REDIS = "Error connecting to Session Service"
ERROR_REQUIRED_DATA_NOT_PROVIDED = 'Please provide valid {}'
ERROR_INVALID_EMAIL = "Please Provide Valid Email Id"
ERROR_UNEXPECTED = "UnExpected error occurred"
ERROR_USER_EXISTS = "User with this Email Address already exists"
ERROR_UNKNOWN_ERROR = "Unknown Error Occurred"
ERROR_TAC_DOCUMENT_NOT_FOUND = "Please accept Terms and conditions!"
ERROR_SESSION_ID_MISSING = "Session Id Missing"
ERROR_SESSION_LOGGING_OUT = "Can't logout. Please contact your Admin"
ERROR_OTP_EXPIRED = "Verification Code is Expired"
ERROR_INVALID_TOKEN = "Invalid reset token"
ERROR_AUTH_TOKEN_MISSING = 'Authorization header is missing'
ERROR_USER_NOT_FOUND_GIVEN_TOKEN = 'No user found for given token'
ERROR_INVALID_LINK = 'Invalid verification link'
ERROR_UID_MISSING = 'UID parameter is missing'
ERROR_INVALID_DATA_FORMAT = 'Invalid questions data format, Expected a list'
ERROR_ALREADY_VERIFIED = 'Invalid attempt: User has already been verified.'
ERROR_USER_ID_MISSING = 'User ID not provided'
ERROR_USER_SURVEY_MISSING = 'User survey not found'
ERROR_CHECK_EMAIL_ALREADY_VERIFIED = "User email is already verified"
ERROR_EMAIL_REQUIRED = "User Email is required'"
